### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#227]
After merging #206, the following compile error happens:
```
/home/chw2lr/code/kuksa.val/src/main.cpp: In function ‘int main(int, const char**)’:
/home/chw2lr/code/kuksa.val/src/main.cpp:269:7: error: reference to ‘thread’ is ambiguous
  269 |       thread http(httpRunServer, variables, httpServer, docRoot, cmdProcessor);
```

**Comment by SebastianSchildt** [comment]
Fixed
